const MOCK_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAAJpklEQVR42u3VsQ2EQAwAweuE5sjp' +
  'nAiJlIAmDDvSFPDc2951XycAQcsTAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgA' +
  'AAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAA' +
  'ACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAAAiAVwAQAAAEAAABAEAAABAAAAQAAAEA' +
  'QAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAAAEAAABAEAAABAA' +
  'AAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAK/QtR27' +
  'RzADHkEAsPyYAQSAzOa/PIUZ8BQCgOXHDCAAZDbf/psBMyAAWH7MAAJAbPPtvxkwAwKA5ccMIADE' +
  'Nt/+mwEzIABYfswAAkBs8+2/GTADAoDlxwwgAMQ23/6bATMgAFh+zAACQGzz7b8ZMAMCgOXHDCAA' +
  'xDbf/psBMyAAWH7MAAJAbPPtvxkwAwKA5ccMIADENt/+mwEzIAB0N9/+mwEzIABYfswAAkBs8+2/' +
  'GTADAoDlxwwgAMQ23/6bATMgAFh+zAACQGzz7b8ZMAMCgOXHDCAAxDbf/psBMyAAWH7MAAJAbPPt' +
  'vxkwAwKA5ccMIADENt/+mwEzIABYfswAAkBs8+2/GTADAoDlxwwgAMQ23/6bATMgAFh+zAACQGzz' +
  '7b8ZMAMCgOXHDCAAxDbf/psBMyAAdDff/psBMyAAWH7MAAJAbPPtvxkwAwKA5ccMIADENt/+mwEz' +
  'IABYfswAAkBs8+2/GTADAoDlxwwgAMQ23/6bATMgAFh+zAACQGzz7b8ZMAMCgOXHDCAAxDbf/psB' +
  'MyAAWH7MAAJAbPPtvxkwAwKA5ccMIADENt/+mwEzIABYfswAAkBs8+2/GTADAoDlxwwgAMQ23/6b' +
  'ATMgAHQ33/6bATMgAFh+zAACQGzz7b8ZMAMCgOXHDCAAxDbf/psBMyAAWH7MAAJAbPPtvxkwAwKA' +
  '5ccMIADENt/+mwEzIABYfswAAkBs8+2/GTADAoDlxwwgAMQ2f9r+T/sxZgABEADLP/QlzYAACAA2' +
  'f8r++xAzgAAIQGX5fZcZQABc/9D++0AzgAAIQGj5fawZQABc/9b++2QzgAAIQGv5fbsZQABcf9AA' +
  'BMD1Bw1AAAQABAABcP1BAxAAAQABQABcf9AABEAAQAAQANcfNAABEAAQAATA9QcNQAAEAARAAHD9' +
  'QQMEAAEAARAAXH/QAAFAAEAABADXHzRAABAAEAABwPUHDRAABAAEQABcfzsMGiAAAgAIgAC4/oAG' +
  'CIDrD2iAAKBbuKQIAK4/GoAA4PqjAQgArj8agADg+qMBCACuPxqAAOD6owEIAK4/GoAA4PqjAQgA' +
  'rj8agAC4/qABAuAVXH/QAAHA9QcNEAAEAAFAAHD90QAEANcfDUAAcP3RAAQA1x8NQAAQAAQAAcD1' +
  'RwMQAFx/NAABQAAQAAQA1x8NQABw/dEABAABQAAQAFx/NAABwPVHAxAABAABQABw/dEABAABQAAQ' +
  'ANcfNAABcP1BAxAAAQABQABcf9AABEAAQAAEANcfNEAAEAAQAAHA9QcNEAAEAARAAHD9QQMEAAEA' +
  'ARAABAABQABw/dEABAABQAAQAFx/NAABQAAQAAQA1x8NQAAQAAQAAUAAEAAEANcfDUAABMBxQQAQ' +
  'AAEAAUAAXH/QAARAAEAAEAABAAFAAFx/0AAEQABAABAAAQABEACvIAAgAAKA6w8aIAAIAAiAACAA' +
  'IAACgACAAAgArj9ogAAgACAAAoAAgAAIAAIAVlgAEAAEAAHA9UcDEAAEAAFAABAABAABQAAQAAQA' +
  'twMBQAAEAAQAAXD9QQMQAAEAAUAABAAEAAEQABAABEAAQAAQAAEAAUAABAAEAAEQABAAAUAAQAAE' +
  'AAEAARAABAAEQAAQABAAAUAAQAAEAAEAARAABAAEQABw/UEDBAANAOssAAgAAoAAIAAIAAKAACAA' +
  'CAACgAAgAAgAAoAACAAIAAIgACAACIAAgAAgAAIAAoAACAAIAAIgACAACIAAgAAgAAIAAoAACAAI' +
  'gACgAeD6CwACAAIgAAgACIAAIAAgAAKAAIAACAACAAIgAGgAuP4CgACAAAgAAoAA2GIBQAAQAAQA' +
  'AUAAEAA0ANcfAUAAEAAEAAFAABAABAABQAA0AFx/BEAAQAAQAAEAAUAABAAEAAHQAHD9EQABAAFA' +
  'AAQABAAB0ABw/REAAQABEAAEAARAANAAcP0FAAEAARAABAAEQADQAHD9BQABAAEQADQA1x8BQAAQ' +
  'AAQADcD1RwAQAAQAAUAAEAAEAA3A9UcAEAAEAAFAA3D9EQAEAAFAANAAXH8EAAFAABAADXCJcP0R' +
  'AAEAAUAANABcfwRAA8D1RwAEAAQAAdAAcP0FAAEAARAANABcfwFAA8D1FwAEAARAANAAXH8EAA3A' +
  '9UcAEAAEAAFAA3D9EQA0ANcfAUAAEAAEAA3A9UcA0ABcfwQADcD1RwDQAFx/BAABQAAQADQA1x8B' +
  'QANw/REANADXHwFAA3D9EQA0ANcfAUADcP0RADQA1x8BQANw/REANMD1RwDQAFx/BAANwPVHANAA' +
  'XH8EAA3A9UcA0ABcfwQADcD1RwCQAZx+BAANwPVHANAAXH8EAA3A9UcAkAGcfgQADcD1RwCQAZx+' +
  'BAANwPVHAJABnH4EAA3A9UcAkAGnHwQAGXD6QQDQANcfBAAZcPpBAJABpx8EABlw+kEAkAGnHwEA' +
  'JXD3EQCQAacfAQAZcPoRAFACdx8BACVw9xEAUAJ3HwEAMXD0EQAIx8AfhABApQf+AgQAEknwvAgA' +
  '/KcWHgEBAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAA' +
  'BAAAAQBAAAAQAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEA' +
  'QAAAEAAABAAAAQBAAAAQAAAEAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAA' +
  'AAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAAB' +
  'AEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABABAAAAQAAAEAQAAAEAAABAAAAQDgOx6/' +
  'jvgOC/Et+gAAAABJRU5ErkJggg==';

// Valid 512x512 placeholder PNG (beige background, cat silhouette).
// Only served when MOCK_GENERATION=1 — real deployments must configure a provider API key.
export async function generateMockCartoonAvatar(_imageBuffer: Buffer, style = 'cartoon') {
  void style;
  await new Promise((resolve) => setTimeout(resolve, 500));
  return Buffer.from(MOCK_PNG_BASE64, 'base64');
}
